import localFont from "next/font/local";
import "../styles/main.scss";
import { Toaster } from "react-hot-toast";
import {Inter} from 'next/font/google';
import AuthProvider from "@/context/AuthProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // className={Inter.className}
      >
        <AuthProvider>
        <Toaster position="top-center" reverseOrder={false} />
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}

export const dynamic = "force-static"